# Generated by Django 3.1.4 on 2021-02-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0004_auto_20210204_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_parent',
        ),
        migrations.RemoveField(
            model_name='images',
            name='tvshow',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='TvShow',
        ),
    ]
