# Generated by Django 3.1.4 on 2021-02-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0007_images_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
