# Generated by Django 3.1.4 on 2021-01-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_episode_season_tvshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='show',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='TvShow',
        ),
    ]
