# Generated by Django 3.1.4 on 2021-01-29 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210129_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_show_name', models.CharField(max_length=250)),
                ('tv_show_slug', models.SlugField(max_length=250, unique_for_date='tv_show_publish')),
                ('tv_show_cover', models.ImageField(null=True, upload_to='upload/')),
                ('tv_show_body', models.TextField()),
                ('tv_show_imdb_rating', models.DecimalField(decimal_places=1, max_digits=12, null=True)),
                ('tv_show_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('tv_show_created', models.DateTimeField(auto_now_add=True)),
                ('tv_show_updated', models.DateTimeField(auto_now=True)),
                ('tv_show_views', models.IntegerField(default=0)),
                ('tv_show_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('tv_show_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_shows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-tv_show_publish',),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='blog.tv_show')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_Show_episode_link', models.CharField(max_length=1000, null=True)),
                ('episode_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_number', to='blog.season')),
            ],
        ),
    ]
