# Generated by Django 3.1.4 on 2021-01-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_episode_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='number',
        ),
        migrations.RemoveField(
            model_name='tv_show',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tv_show',
            name='tv_show_author',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Tv_Show',
        ),
    ]
