# Generated by Django 3.1.4 on 2021-01-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tvshow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TvShow',
        ),
    ]
