# Generated by Django 3.1.4 on 2021-01-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
