# Generated by Django 3.1.4 on 2021-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvshowsclassifier',
            options={'ordering': ('-create_at',)},
        ),
        migrations.AddField(
            model_name='tvshowsclassifier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
