# Generated by Django 3.1.4 on 2021-02-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20210211_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
